services:
  redis:
    image: redis:latest
    container_name: redis
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5
    ports:
      - "6379:6379"

  publisher:
    build: 
      context: ../
      dockerfile: ./SampleStack.Redis/Dockerfile
    deploy: 
      replicas: 2
    environment:
      - MODE=PUB
    depends_on:
      - subscriber

  subscriber:
    build: 
      context: ../
      dockerfile: ./SampleStack.Redis/Dockerfile
    container_name: redis_subscriber
    environment:
      - MODE=SUB
    depends_on:
      redis:
        condition: service_healthy
