services:
  redis:
    image: redis:latest
    container_name: redis
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5
    ports:
      - "6379:6379"

  publisher:
    image: pubsub-app:latest
    deploy: 
      replicas: 2
    environment:
      - MODE=PUB
      - REDIS_HOST=redis:6379
    depends_on:
      - subscriber

  subscriber:
    image: pubsub-app:latest
    container_name: redis_subscriber
    environment:
      - MODE=SUB
      - REDIS_HOST=redis:6379
    depends_on:
      redis:
        condition: service_healthy
